output   = "../../../pkg/db/postgresmodel"
wipe     = true
no-tests = true
pkgname  = "postgresmodel"

[psql]
  dbname = "superaidskrebs"
  host   = "localhost"
  port   = 5432
  user   = "superaidskrebs"
  pass   = "superaidskrebs4223"
  blacklist = ["migrations"]
  sslmode = "disable"