// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package postgresmodel

var TableNames = struct {
	Channels   string
	Clicks     string
	LinkHasTag string
	Links      string
	Tags       string
	Users      string
}{
	Channels:   "Channels",
	Clicks:     "Clicks",
	LinkHasTag: "LinkHasTag",
	Links:      "Links",
	Tags:       "Tags",
	Users:      "Users",
}
